### ISSUE TITLE
gget fails with "invalid cross-device link" when moving files between devices

### ISSUE THREAD

**Issue by s4heid** [dpb587/gget#1]
Came across this issue when running `dpb587/gget` in GitHub actions.

**Error log:**

```
panic: downloading delegatebot-0.9.0-linux-amd64: processing step 2: renaming: rename /tmp/gget-tmpfile-168433803 delegatebot: invalid cross-device link
goroutine 37 [running]:
github.com/dpb587/gget/cmd/gget.(*Command).Execute.func2(0xc00000e230, 0xc0001d6eb0, 0xa02260, 0xc000094020)
	/root/cmd/gget/command.go:248 +0x243
created by github.com/dpb587/gget/cmd/gget.(*Command).Execute
	/root/cmd/gget/command.go:241 +0x1193
```

It seems that the use of `os.Rename()` is the problem, see [relevant code](https://github.com/dpb587/gget/blob/a0f872daf3fe5eb8dcdefc7d0df1a52058e8845c/pkg/downloader/installer_rename.go#L22-L25).

**Comment by dpb587** [comment]
Fixed in https://github.com/dpb587/gget/commit/4d04641341dd0e0afd2d380938de2a396ed18c10.

**Comment by s4heid** [comment]
thanks! that was fast.
