### ISSUE TITLE
List of real-world checksum file variations

### ISSUE THREAD

**Issue by ghost** [dpb587/gget#10]
I saw that you're planning to add support for `sha256sums.txt` and `sha512sums.txt` files in v0.4.0 so I thought it might be helpful to share some of the variations I've encountered while working on my script.

This is not meant to be a feature request to add support for these variations, just a list that you can use as a reference in case you do want to support more variations in `gget`.

`*.md5`
`*.sha256`
**Example:** https://github.com/genuinetools/reg/releases/tag/v0.16.1

`*_sha256.txt`
`*_sha512.txt`
**Example:** https://github.com/hairyhenderson/gomplate/releases/tag/v3.7.0

`shasums`
**Example:** https://github.com/gdrive-org/gdrive/releases/tag/2.1.0

`CHECKSUM`
**Example:** https://github.com/vmware-tanzu/velero/releases/tag/v1.4.0

`MD5SUMS`
`SHA1SUMS`
`SHA256SUMS`
**Example:** https://github.com/rclone/rclone/releases/tag/v1.52.1

`md5sum.txt`
`sha256sum.txt`
**Example:** https://github.com/docker/machine/releases/tag/v0.16.2

**Comment by dpb587** [comment]
Thanks - this is helpful. I had some refactoring in mind for this part of code and added a few conventions that I recognized as part of that. I'll revisit this again once I finish some reports on broader usage of some of the other conventions.
