### ISSUE TITLE
[Request] Add repository for gget's website

### ISSUE THREAD

**Issue by ghost** [dpb587/gget#16]
First, let me say that the new website for `gget` is gorgeous. I love the design, the color choices, the flow. Fantastic work! Having said that, there are two reasons why I think that the source for it should be public.

The first one is altruistic: because it would allow people to submit pull requests for it to improve/update the documentation for `gget` when necessary.

The second one is selfish: because this gave me the idea of making a website for my little script as well (primarily because .sh is an actual TLD, making `https://ginstall.sh/` a valid domain name and how neat would that be?) and I would love to use that design as a template for it.

**Comment by dpb587** [comment]
Thanks - I appreciate the positive feedback.

You can find the code for it in the [`website` directory](https://github.com/dpb587/gget/tree/master/website). I was more focused on getting something out there building off prior experience, so you can probably find better and cleaner technical ways to accomplish such a site. For styling, it's built with [Tailwind CSS](https://tailwindcss.com/) (and [Tailwind UI](https://tailwindui.com/) significantly helped make it better, faster), and icons are licensed from [Font Awesome](https://fontawesome.com/).

Good luck publishing your site - `ginstall.sh` looks like an ideal match, for sure. I'll keep an eye out for it.
