### ISSUE TITLE
Can't find resources for cloudfoundry/cli

### ISSUE THREAD

**Issue by pianohacker** [dpb587/gget#2]
```console
$ gget cloudfoundry/cli 
gget: error: expected matching resources: no resource matched: *

$ gget cloudfoundry/cli --show-resources
gget: error: expected matching resources: no resource matched: *

$ gget cloudfoundry/cli --show-ref
tag     v6.51.0
commit  2acd15650eef815159ecd5a83d021ac456280729
```

**Comment by dpb587** [comment]
It looks like that repo does not upload assets to their releases so the failure is expected (they include S3 binary links in their release note, which this doesn't support).  If you're intending to download an archive of the source from the tag, you can use the `--type=archive` option.
