### ISSUE TITLE
Show canonical reference when downloading

### ISSUE THREAD

**Issue by dpb587** [dpb587/gget#4]
It would be helpful to report what reference was ultimately used when downloading. For example: when auditing historical logs; `latest` isn't explicit; versions are not implied in file names; seeing canonical user/repo capitalization; or seeing the expanded commit hash.

Might be a good place to include the number of files (and total download size, if known), too? Maybe with a non-present continuous verb? Probably should not be printed in `--quiet` mode. Review messaging with wget/curl output. Some ideas:

```
$ gget github.com/dpb587/gget
Downloading 3 files (34 MB) from github.com/dpb587/gget@v0.3.0...
...

$ gget github.com/dpb587/gget@36c7 README.md
Found github.com/dpb587/gget@36c7ac4821a5ce437303c3da920efbbadcb2a873
...

$ gget github.com/DPB587/GGET
Using github.com/dpb587/gget@v0.3.0
...

$ gget github.com/dpb587/gget
...
Downloaded 3 files from github.com/dpb587/gget@v0.3.0
```

**Comment by dpb587** [comment]
cc @whalehub

**Comment by ghost** [comment]
@dpb587 I like the first variant best. It's both concise and has all the information a user might want. 👍
